language: julia
julia:
    - release
    - nightly
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("Jld2Mat")'
    - if [ -f test/runtests.jl ]; then
        julia --check-bounds=yes -e 'Pkg.test("Jld2Mat")'
      fi
